apiVersion: v1
kind: Namespace
metadata:
  name: leaf
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: leaf
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: aadarshg619/ml-backend2:latest
        ports:
        - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: backend-svc
  namespace: leaf
spec:
  selector:
    app: backend
  ports:
  - port: 8000
    targetPort: 8000
  type: ClusterIP
