apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: leaf
  name: backend-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app.kubernetes.io/name: backend
  template:
    metadata:
      labels:
        app.kubernetes.io/name: backend
    spec:
      containers:
      - name: backend
        image: aadarshg619/ml-backend3:latest
        ports:
        - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  namespace: leaf
  name: backend-svc
spec:
  ports:
  - port: 8000
    targetPort: 8000
    protocol: TCP
  type: ClusterIP
  selector:
    app.kubernetes.io/name: backend
