apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  labels:
    app: ml-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ml-backend
  template:
    metadata:
      labels:
        app: ml-backend
    spec:
      containers:
      - name: ml-backend-container
        image: aadarshg619/ml-backend2:latest
        ports:
        - containerPort: 8000
---

apiVersion: v1
kind: Service
metadata:
  name: backend-svc # ✅ This must match what the React app expects
spec:
  type: ClusterIP
  selector:
    app: ml-backend
  ports:
  - port: 8000
    targetPort: 8000
