apiVersion: v1
kind: Service
metadata:
  name: ml-backend-service
spec:
  type: NodePort
  selector:
    app: ml-backend
  ports:
    - port: 80 # External-facing service port (optional)
      targetPort: 8000 # Internal container port
      nodePort: 30080 # Fixed NodePort (accessible via <EC2_IP>:30080)
